import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "Dynamic - Blog - Website using NextJs",
  description: "Generated by hammadhafeez",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
      
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
